
# DEB
#set(CPACK_DEBIAN_PACKAGE_DEPENDS libstdc++ libm libc)
set(CPACK_DEB_COMPONENT_INSTALL YES)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)

# RPM
set(CPACK_RPM_COMPONENT_INSTALL YES)

# NSIS
#set(CPACK_NSIS_COMPONENT_INSTALL ON)
set(CPACK_COMPONENT_cli_DISABLED YES)

# ZIP
set(CPACK_ARCHIVE_COMPONENT_INSTALL YES)

install(
	TARGETS pixelmapcli
	RUNTIME DESTINATION bin
	COMPONENT cli
)

include(CPack)
