
# DEB
#set(CPACK_DEBIAN_PACKAGE_DEPENDS libstdc++ libm libc)
set(CPACK_DEB_COMPONENT_INSTALL YES)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)

# RPM
set(CPACK_RPM_COMPONENT_INSTALL YES)

# NSIS
#set(CPACK_NSIS_COMPONENT_INSTALL ON)
set(CPACK_COMPONENT_cli_DISABLED YES)

# ZIP
set(CPACK_ARCHIVE_COMPONENT_INSTALL YES)

install(
	TARGETS pixelmapcli
	RUNTIME DESTINATION bin
	COMPONENT cli
)

# Licenses
install(FILES "${CMAKE_SOURCE_DIR}/LICENSE" TYPE DOC COMPONENT cli RENAME "pixelmap.txt")
install(FILES "${ZLIB_LICENSE_FILE}" TYPE DOC COMPONENT cli RENAME "zlib.txt")
if (PIXELMAP_USE_LIBDEFLATE)
	install(FILES "${DEFLATE_LICENSE_FILE}" TYPE DOC COMPONENT cli RENAME "deflate.txt")
endif()
install(FILES "${LZ4_LICENSE_FILE}" TYPE DOC COMPONENT cli RENAME "lz4.txt")
install(FILES "${PNG_LICENSE_FILE}" TYPE DOC COMPONENT cli RENAME "png.txt")
install(FILES "${GLM_LICENSE_FILE}" TYPE DOC COMPONENT cli RENAME "glm.txt")
install(FILES "${FMT_LICENSE_FILE}" TYPE DOC COMPONENT cli RENAME "fmt.txt")
install(FILES "${SPDLOG_LICENSE_FILE}" TYPE DOC COMPONENT cli RENAME "spdlog.txt")
install(FILES "${SPDMON_LICENSE_FILE}" TYPE DOC COMPONENT cli RENAME "spdmon.txt")
if (PIXELMAP_BUILD_TESTS)
	install(FILES "${CATCH2_LICENSE_FILE}" TYPE DOC COMPONENT cli RENAME "catch2.txt")
endif()
if (OPENLAYERS_LICENSE)
	install(FILES "${OPENLAYERS_LICENSE}" TYPE DOC COMPONENT cli RENAME "openlayers.txt")
endif()

include(CPack)
