---
name: Build

on:
  push:
    branches:
      - main

jobs:
  Tests:
    runs-on: linux-gtk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build
        run: mkdir build
      - name: Cache cmake
        uses: actions/cache@v4
        with:
          path: build
          key: tests-${{ hashFiles('CMakeLists.txt', 'library/**/CMakeLists.txt', 'cli/**/CMakeLists.txt', 'gui/**/CMakeLists.txt') }}
      - name: Cmake
        working-directory: ./build
        run: cmake -Wno-dev -DCMAKE_BUILD_TYPE=Release -DPIXELMAP_BUILD_GUI=OFF ..
      - name: Compile tests
        working-directory: ./build
        run: make -j$(nproc) tests
      - name: Test
        working-directory: ./build
        run: ctest --output-on-failure

  Linux:
    runs-on: linux-gtk
    needs: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build
        run: mkdir build
      - name: Cache cmake
        uses: actions/cache@v4
        with:
          path: build
          key: linux-${{ hashFiles('CMakeLists.txt', 'library/**/CMakeLists.txt', 'cli/**/CMakeLists.txt', 'gui/**/CMakeLists.txt') }}
      - name: Cmake
        working-directory: ./build
        run: cmake -Wno-dev -DCMAKE_BUILD_TYPE=Release -DPIXELMAP_BUILD_TESTS=OFF ..
      - name: Compile CLI
        working-directory: ./build
        run: |
          make -j$(nproc) pixelmapcli
          strip pixelmapcli
      - name: Compile GUI
        working-directory: ./build
        run: |
          make -j$(nproc) pixelmapim
          strip pixelmapim
      - name: Upload CLI
        uses: actions/upload-artifact@v3
        with:
          name: pixelmapcli-linux-continuous
          path: build/pixelmapcli
      - name: Upload GUI
        uses: actions/upload-artifact@v3
        with:
          name: pixelmapim-linux-continuous
          path: build/pixelmapim

  Windows:
    runs-on: windows-cross
    needs: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build
        run: mkdir build
      - name: Cache cmake
        uses: actions/cache@v4
        with:
          path: build
          key: win-${{ hashFiles('CMakeLists.txt', 'library/**/CMakeLists.txt', 'cli/**/CMakeLists.txt', 'gui/**/CMakeLists.txt') }}
      - name: Cmake
        working-directory: ./build
        run: cmake -Wno-dev -DCMAKE_BUILD_TYPE=Release -DPIXELMAP_BUILD_TESTS=OFF ..
      - name: Compile CLI
        working-directory: ./build
        run: |
          make -j$(nproc) pixelmapcli
          strip pixelmapcli.exe
      - name: Compile GUI
        working-directory: ./build
        run: |
          make -j$(nproc) pixelmapim
          strip pixelmapim.exe
      - name: Upload CLI
        uses: actions/upload-artifact@v3
        with:
          name: pixelmapcli-win-continuous
          path: build/pixelmapcli.exe
      - name: Upload GUI
        uses: actions/upload-artifact@v3
        with:
          name: pixelmapim-win-continuous
          path: build/pixelmapim.exe
