---
name: Build

on:
  push:
    branches:
      - main

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: |
          apt-get update
          apt-get install -y build-essential cmake libsdl2-dev libgtk-3-dev
      - name: Create build
        run: mkdir build
      - name: Cmake
        working-directory: ./build
        run: cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: Compile tests
        working-directory: ./build
        run: make -j$(nproc) tests
      - name: Test
        working-directory: ./build
        run: ./tests
      - name: Compile CLI
        working-directory: ./build
        run: make -j$(nproc) pixelmapcli
      - name: Compile GUI
        working-directory: ./build
        run: make -j$(nproc) pixelmapim

  Windows:
    runs-on: windows-cross
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build
        run: mkdir build
      - name: Cmake
        working-directory: ./build
        run: cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: Compile tests
        working-directory: ./build
        run: make -j$(nproc) tests
      - name: Test
        working-directory: ./build
        run: ./tests
      - name: Compile CLI
        working-directory: ./build
        run: make -j$(nproc) pixelmapcli
      - name: Compile GUI
        working-directory: ./build
        run: make -j$(nproc) pixelmapim