---
name: Build

on:
  push:
    branches:
      - main

jobs:
  Tests:
    runs-on: linux-gtk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build
        run: mkdir build
      - name: Cache cmake
        uses: actions/cache@v4
        with:
          path: build
          key: >-
            tests-${{
              hashFiles(
                'CMakeLists.txt',
                'library/**/CMakeLists.txt',
                'library/**/*.cmake',
                'cli/**/CMakeLists.txt',
                'cli/**/*.cmake',
                'gui/**/CMakeLists.txt',
                'gui/**/*.cmake'
              )
            }}
      - name: Cmake
        working-directory: ./build
        run: cmake -Wno-dev -DCMAKE_BUILD_TYPE=Release -DPIXELMAP_BUILD_GUI=OFF ..
      - name: Compile tests and cli
        working-directory: ./build
        run: make -j$(nproc) tests pixelmapcli
      - name: Test
        working-directory: ./build
        run: ctest --output-on-failure

  Linux:
    runs-on: linux-gtk
    needs: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build
        run: mkdir build
      - name: Cache cmake
        uses: actions/cache@v4
        with:
          path: build
          key: >-
            linux-${{
              hashFiles(
                'CMakeLists.txt',
                'library/**/CMakeLists.txt',
                'library/**/*.cmake',
                'cli/**/CMakeLists.txt',
                'cli/**/*.cmake',
                'gui/**/CMakeLists.txt',
                'gui/**/*.cmake'
              )
            }}
      - name: Cmake
        working-directory: ./build
        run: cmake -Wno-dev -DCMAKE_BUILD_TYPE=Release -DPIXELMAP_BUILD_TESTS=OFF -DPIXELMAP_INSTALL=ON ..
      - name: Compile CLI
        working-directory: ./build
        run: |
          make -j$(nproc) pixelmapcli
          strip pixelmapcli
      - name: Compile GUI
        working-directory: ./build
        run: |
          make -j$(nproc) pixelmapim
          strip pixelmapim
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pixelmap-linux-continuous
          path: |
            build/pixelmapcli
            build/pixelmapim
      - name: Package binaries
        working-directory: ./build
        run: cpack -G "DEB;RPM;ZIP" -D CPACK_COMPONENTS_ALL="cli;gui"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pixelmap-linux-pkg
          path: |
            build/PixelMap-*.deb
            build/PixelMap-*.rpm
            build/PixelMap-*.zip

  Windows:
    runs-on: windows-cross
    needs: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build
        run: mkdir build
      - name: Cache cmake
        uses: actions/cache@v4
        with:
          path: build
          key: >-
            win-${{
              hashFiles(
                'CMakeLists.txt',
                'library/**/CMakeLists.txt',
                'library/**/*.cmake',
                'cli/**/CMakeLists.txt',
                'cli/**/*.cmake',
                'gui/**/CMakeLists.txt',
                'gui/**/*.cmake'
              )
            }}
      - name: Cmake
        working-directory: ./build
        run: cmake -Wno-dev -DCMAKE_BUILD_TYPE=Release -DPIXELMAP_BUILD_TESTS=OFF -DPIXELMAP_INSTALL=ON ..
      - name: Compile CLI
        working-directory: ./build
        run: |
          make -j$(nproc) pixelmapcli
          strip pixelmapcli.exe
      - name: Compile GUI
        working-directory: ./build
        run: |
          make -j$(nproc) pixelmapim
          strip pixelmapim.exe
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pixelmap-win-continuous
          path: |
            build/pixelmapcli.exe
            build/pixelmapim.exe
      - name: Package binaries
        working-directory: ./build
        run: cpack -G "NSIS;ZIP" -D CPACK_COMPONENTS_ALL="cli;gui"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pixelmap-win-pkg
          path: |
            build/PixelMap-*.exe
            build/PixelMap-*.zip
