---
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the release
        type: string
        required: yes

jobs:
  Linux:
    runs-on: linux-gtk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build
        run: mkdir -p build/publish
      - name: Cmake
        run: cmake --preset package
      - name: Compile
        run: cmake --build --preset default --parallel $(nproc)
      - name: Package binaries
        run: cpack --preset linux
      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: pixelmap-linux-release
          compression-level: 0
          path: build/publish/*

  Windows:
    runs-on: windows-cross
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build
        run: mkdir -p build/publish
      - name: Cmake
        run: cmake --preset package
      - name: Compile
        run: cmake --build --preset default --parallel $(nproc)
      - name: Package binaries
        run: cpack --preset windows
      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: pixelmap-win-release
          compression-level: 0
          path: build/publish/*

  Release:
    runs-on: linux
    needs:
      - Linux
      - Windows
    steps:
      - name: Fetch artifacts
        uses: actions/download-artifact@v3
        with:
          name: pixelmap-linux-release
          path: ./publish
      - name: Fetch artifacts
        uses: actions/download-artifact@v3
        with:
          name: pixelmap-win-release
          path: ./publish
      - name: Release publicly
        uses: https://github.com/Dylan700/sftp-upload-action@latest
        with:
          server: ${{ vars.webserver }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          port: 22
          uploads: |
            ./publish/ => ${{ vars.release_path }}${{ inputs.version }}
