
# DEB
#set(CPACK_DEBIAN_PACKAGE_DEPENDS libstdc++ libm libc)
set(CPACK_DEB_COMPONENT_INSTALL YES)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)

# RPM
set(CPACK_RPM_COMPONENT_INSTALL YES)

# NSIS
#set(CPACK_NSIS_COMPONENT_INSTALL ON)
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")

# ZIP
set(CPACK_ARCHIVE_COMPONENT_INSTALL YES)

install(
	TARGETS pixelmapim
	RUNTIME DESTINATION bin
	COMPONENT gui
)

# Licenses
install(FILES "${CMAKE_SOURCE_DIR}/LICENSE" TYPE DOC COMPONENT gui RENAME "pixelmap.txt")
install(FILES "${ZLIB_LICENSE_FILE}" TYPE DOC COMPONENT gui RENAME "zlib.txt")
if (PIXELMAP_USE_LIBDEFLATE)
	install(FILES "${DEFLATE_LICENSE_FILE}" TYPE DOC COMPONENT gui RENAME "deflate.txt")
endif()
install(FILES "${LZ4_LICENSE_FILE}" TYPE DOC COMPONENT gui RENAME "lz4.txt")
install(FILES "${PNG_LICENSE_FILE}" TYPE DOC COMPONENT gui RENAME "png.txt")
install(FILES "${GLM_LICENSE_FILE}" TYPE DOC COMPONENT gui RENAME "glm.txt")
install(FILES "${FMT_LICENSE_FILE}" TYPE DOC COMPONENT gui RENAME "fmt.txt")
install(FILES "${SPDLOG_LICENSE_FILE}" TYPE DOC COMPONENT gui RENAME "spdlog.txt")
if (PIXELMAP_BUILD_TESTS)
	install(FILES "${CATCH2_LICENSE_FILE}" TYPE DOC COMPONENT gui RENAME "catch2.txt")
endif()
if (SDL2_LICENSE_FILE)
	install(FILES "${SDL2_LICENSE_FILE}" TYPE DOC COMPONENT gui RENAME "sdl2.txt")
endif()
install(FILES "${IMGUI_LICENSE_FILE}" TYPE DOC COMPONENT gui RENAME "imgui.txt")
install(FILES "${NFD_LICENSE_FILE}" TYPE DOC COMPONENT gui RENAME "nfd.txt")

include(CPack)
